# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Display parameters
        shell: bash
        run: echo "${{ format('<h1>Parameters</h1><p>{0}</p>', tojson(inputs)) }}" > "$GITHUB_STEP_SUMMARY"
      - name: debug
        run: |
          # print inputs
          echo "inputs: ${{ toJson(inputs) }}"
          echo "==${XX_DEBUG}=="
          echo "==${XX_GITHUB_DATA_REPO}=="
