# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:

env:
  XX_BRANCH_NAME_PREFIX: 'branch_trains_search_keyword_response'
  XX_GITHUB_OWNER: ${{ secrets.XX_GITHUB_OWNER }}
  XX_CI_GH_PAT: ${{ secrets.XX_CI_GH_PAT }}
  XX_DEBUG: ${{ vars.XX_DEBUG }}
  XX_GITHUB_DATA_REPO: ${{ vars.XX_GITHUB_DATA_REPO }}
  XX_GITHUB_PROGRAM_REPO: ${{ vars.XX_GITHUB_PROGRAM_REPO }}

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Display parameters
        shell: bash
        run: echo "${{ format('<h1>Parameters</h1><p>{0}</p>', tojson(inputs)) }}" > "$GITHUB_STEP_SUMMARY"
      - name: debug
        run: |
          # print inputs
          echo "inputs: ${{ toJson(inputs) }}"
          echo "==${XX_DEBUG}=="
          echo "==${XX_GITHUB_DATA_REPO}=="
